version: "3.9"
services:
   web:
      container_name: web-container
      build: .
      ports:
         - "3000:3000"
      environment:
         PORT: 3000
         POSTGRES_DB: quotes
         POSTGRES_USER: root
         POSTGRES_PASSWORD: root
         POSTGRES_HOST: db
         POSTGRES_PORT: 5432
      volumes:
         - .:/app
         - /app/node_modules
      depends_on:
         - db

   db:
      image: postgres:16
      container_name: postgres-container
      environment:
         POSTGRES_USER: root
         POSTGRES_PASSWORD: root
         POSTGRES_DB: quotes
      ports:
         # the host port is 5431 because the local port 5432 is already in use
         - "5431:5432"

      volumes:
         - postgres-data:/var/lib/postgresql/data

volumes:
   postgres-data:
